@echo off
echo Stopping Django server...
echo Please press Ctrl+C in the Django server terminal to stop it first
pause

echo Fetching changes from remote repository...
git fetch origin

echo Checking for updates...
git status

echo Pulling latest changes...
git pull origin main

echo Installing/updating dependencies...
pip install -r requirements.txt

echo Applying migrations...
python manage.py migrate

echo Starting Django server...
python manage.py runserver
