# Generated by Django 4.2.7 on 2025-10-12 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
