# Generated by Django 4.2.7 on 2025-10-12 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "participants_count",
                    models.IntegerField(verbose_name="Количество участников"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "alcohol",
                    models.BooleanField(default=False, verbose_name="Алкоголь"),
                ),
                ("host", models.BooleanField(default=False, verbose_name="Ведущий")),
                (
                    "decoration",
                    models.BooleanField(default=False, verbose_name="Декорации"),
                ),
                (
                    "music",
                    models.BooleanField(
                        default=False, verbose_name="Музыкальное сопровождение"
                    ),
                ),
                (
                    "photographer",
                    models.BooleanField(default=False, verbose_name="Фотограф"),
                ),
                (
                    "catering",
                    models.BooleanField(default=False, verbose_name="Кейтеринг"),
                ),
                (
                    "sound_equipment",
                    models.BooleanField(
                        default=False, verbose_name="Звуковое оборудование"
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Особые пожелания"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-created_at"],
            },
        ),
    ]
