# Generated by Django 4.2.7 on 2025-10-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения обратной связи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("hero", "Главный баннер"),
                            ("about", "О ресторане"),
                            ("services", "Услуги"),
                            ("contact", "Контакты"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Тип контента",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Подзаголовок"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="content/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Контент сайта",
                "verbose_name_plural": "Контент сайта",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                ("bio", models.TextField(verbose_name="Биография")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="team/", verbose_name="Фото"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Член команды",
                "verbose_name_plural": "Команда",
                "ordering": ["order", "name"],
            },
        ),
    ]
