# Generated by Django 4.2.7 on 2025-10-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_contactmessage_sitecontent_teammember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpreferences",
            name="preferred_zone",
            field=models.CharField(
                choices=[
                    ("regular", "Обычная зона"),
                    ("vip", "VIP зона"),
                    ("bar", "Барная зона"),
                ],
                default="regular",
                max_length=10,
                verbose_name="Предпочитаемая зона",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="zone",
            field=models.CharField(
                choices=[
                    ("regular", "Обычная зона"),
                    ("vip", "VIP зона"),
                    ("bar", "Барная зона"),
                ],
                max_length=10,
                verbose_name="Зона",
            ),
        ),
    ]
