# Generated by Django 5.2.3 on 2025-10-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_bookingpreferences_preferred_zone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Главная страница"),
                            ("about", "О ресторане"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Страница",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("subtitle", models.TextField(blank=True, verbose_name="Подзаголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("services", models.TextField(blank=True, verbose_name="Услуги")),
                ("contacts", models.TextField(blank=True, verbose_name="Контакты")),
                ("history", models.TextField(blank=True, verbose_name="История")),
                (
                    "mission",
                    models.TextField(blank=True, verbose_name="Миссия и ценности"),
                ),
                ("team", models.TextField(blank=True, verbose_name="Команда")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Контент страницы",
                "verbose_name_plural": "Контент страниц",
                "ordering": ["page"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Сообщение обратной связи",
                "verbose_name_plural": "Сообщения обратной связи",
            },
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="is_read",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новое"),
                    ("read", "Прочитано"),
                    ("replied", "Отвечено"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
    ]
