# Generated by Django 5.2.3 on 2025-10-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_pagecontent_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpreferences",
            name="preferred_zone",
            field=models.CharField(
                choices=[("regular", "Обычная зона"), ("vip", "VIP зона")],
                default="regular",
                max_length=10,
                verbose_name="Предпочитаемая зона",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="zone",
            field=models.CharField(
                choices=[("regular", "Обычная зона"), ("vip", "VIP зона")],
                max_length=10,
                verbose_name="Зона",
            ),
        ),
    ]
